[package]
name = "provision"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14", features = ["canvas"] }
iced_fonts = { version = "0.3", features = ["lucide"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
